import { PrismaClient, Platform } from '@prisma/client';
const db = new PrismaClient();

function getProducts() {
  return [
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17258',
      name: 'Wiedźmin 3: Dziki Gon',
      language: 'PL',
      pegi: 18,
      description:
        'Gra action RPG, stanowiąca trzecią część przygód Geralta z Rivii. Podobnie jak we wcześniejszych odsłonach cyklu, Wiedźmin 3: Dziki Gon bazuje na motywach twórczości literackiej Andrzeja Sapkowskiego, jednak nie jest bezpośrednią adaptacją żadnej z jego książek.',
      mainPicture: 'Witcher3PC.jpg',
      inStock: 10,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'Witcher3_1.jpg',
      pictureTwo: 'Witcher3_2.jpg',
      pictureThree: 'Witcher3_3.jpg',
      pictureFour: 'Witcher3_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17267',
      name: 'Wiedźmin 3: Dziki Gon',
      language: 'PL',
      pegi: 18,
      description:
        'Gra action RPG, stanowiąca trzecią część przygód Geralta z Rivii. Podobnie jak we wcześniejszych odsłonach cyklu, Wiedźmin 3: Dziki Gon bazuje na motywach twórczości literackiej Andrzeja Sapkowskiego, jednak nie jest bezpośrednią adaptacją żadnej z jego książek.',
      mainPicture: 'Witcher3XBOX.jpg',
      inStock: 10,
      platform: Platform.XBOX,
      price: 259.99,
      pictureOne: 'Witcher3_1.jpg',
      pictureTwo: 'Witcher3_2.jpg',
      pictureThree: 'Witcher3_3.jpg',
      pictureFour: 'Witcher3_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17266',
      name: 'Wiedźmin 3: Dziki Gon',
      language: 'PL',
      pegi: 18,
      description:
        'Gra action RPG, stanowiąca trzecią część przygód Geralta z Rivii. Podobnie jak we wcześniejszych odsłonach cyklu, Wiedźmin 3: Dziki Gon bazuje na motywach twórczości literackiej Andrzeja Sapkowskiego, jednak nie jest bezpośrednią adaptacją żadnej z jego książek.',
      mainPicture: 'Witcher3PS.jpg',
      inStock: 10,
      platform: Platform.PLAYSTATION,
      price: 259.99,
      pictureOne: 'Witcher3_1.jpg',
      pictureTwo: 'Witcher3_2.jpg',
      pictureThree: 'Witcher3_3.jpg',
      pictureFour: 'Witcher3_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17257',
      name: 'Cyberpunk 2077',
      language: 'PL',
      pegi: 18,
      description:
        'Cyberpunk 2077 to gra RPG akcji osadzona w otwartym świecie, która jest dziełem studia CD Projekt RED, odpowiedzialnego za całą serię Wiedźmin. Tytuł ukazał się na platformach PC, PS4 i XONE.',
      mainPicture: 'Cyberpunk2077PC.jpg',
      inStock: 7,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'Cyberpunk2077_1.jpg',
      pictureTwo: 'Cyberpunk2077_2.jpg',
      pictureThree: 'Cyberpunk2077_3.jpg',
      pictureFour: 'Cyberpunk2077_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17246',
      name: 'Cyberpunk 2077',
      language: 'PL',
      pegi: 18,
      description:
        'Cyberpunk 2077 to gra RPG akcji osadzona w otwartym świecie, która jest dziełem studia CD Projekt RED, odpowiedzialnego za całą serię Wiedźmin. Tytuł ukazał się na platformach PC, PS4 i XONE.',
      mainPicture: 'Cyberpunk2077XBOX.jpg',
      inStock: 7,
      platform: Platform.XBOX,
      price: 259.99,
      pictureOne: 'Cyberpunk2077_1.jpg',
      pictureTwo: 'Cyberpunk2077_2.jpg',
      pictureThree: 'Cyberpunk2077_3.jpg',
      pictureFour: 'Cyberpunk2077_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17245',
      name: 'Cyberpunk 2077',
      language: 'PL',
      pegi: 18,
      description:
        'Cyberpunk 2077 to gra RPG akcji osadzona w otwartym świecie, która jest dziełem studia CD Projekt RED, odpowiedzialnego za całą serię Wiedźmin. Tytuł ukazał się na platformach PC, PS4 i XONE.',
      mainPicture: 'Cyberpunk2077PS.jpg',
      inStock: 7,
      platform: Platform.PLAYSTATION,
      price: 259.99,
      pictureOne: 'Cyberpunk2077_1.jpg',
      pictureTwo: 'Cyberpunk2077_2.jpg',
      pictureThree: 'Cyberpunk2077_3.jpg',
      pictureFour: 'Cyberpunk2077_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17256',
      name: 'Grand Theft Auto V',
      language: 'PL',
      pegi: 18,
      description:
        'Grand Theft Auto V to najnowsza odsłona jednej z najpopularniejszych i najbardziej kontrowersyjnych serii w historii gier wideo. Tytuł został wyprodukowany przez studio Rockstar North, a wydaniem zajęła się firma Rockstar Games.',
      mainPicture: 'GTA5PC.jpg',
      inStock: 3,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'GTA5_1.jpg',
      pictureTwo: 'GTA5_2.jpg',
      pictureThree: 'GTA5_3.jpg',
      pictureFour: 'GTA5_4.jpg',
      pictureFive: 'GTA5_5.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17356',
      name: 'Grand Theft Auto V',
      language: 'PL',
      pegi: 18,
      description:
        'Grand Theft Auto V to najnowsza odsłona jednej z najpopularniejszych i najbardziej kontrowersyjnych serii w historii gier wideo. Tytuł został wyprodukowany przez studio Rockstar North, a wydaniem zajęła się firma Rockstar Games.',
      mainPicture: 'GTA5XBOX.jpg',
      inStock: 3,
      platform: Platform.XBOX,
      price: 259.99,
      pictureOne: 'GTA5_1.jpg',
      pictureTwo: 'GTA5_2.jpg',
      pictureThree: 'GTA5_3.jpg',
      pictureFour: 'GTA5_4.jpg',
      pictureFive: 'GTA5_5.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17345',
      name: 'Grand Theft Auto V',
      language: 'PL',
      pegi: 18,
      description:
        'Grand Theft Auto V to najnowsza odsłona jednej z najpopularniejszych i najbardziej kontrowersyjnych serii w historii gier wideo. Tytuł został wyprodukowany przez studio Rockstar North, a wydaniem zajęła się firma Rockstar Games.',
      mainPicture: 'GTA5PS.jpg',
      inStock: 3,
      platform: Platform.PLAYSTATION,
      price: 259.99,
      pictureOne: 'GTA5_1.jpg',
      pictureTwo: 'GTA5_2.jpg',
      pictureThree: 'GTA5_3.jpg',
      pictureFour: 'GTA5_4.jpg',
      pictureFive: 'GTA5_5.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17255',
      name: 'The Elder Scrolls V: Skyrim',
      language: 'PL',
      pegi: 18,
      description:
        'The Elder Scrolls V: Skyrim to piąta część popularnego cyklu gier RPG studia Bethesda Softworks. Podobnie jak w przypadku poprzednich odsłon, gracz ma okazję wcielić się w bohatera, który ma za zadanie ocalić świat przed zagładą.',
      mainPicture: 'SkyrimPC.jpg',
      inStock: 0,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'Skyrim_1.jpg',
      pictureTwo: 'Skyrim_2.jpg',
      pictureThree: 'Skyrim_3.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a27255',
      name: 'The Elder Scrolls V: Skyrim',
      language: 'PL',
      pegi: 18,
      description:
        'The Elder Scrolls V: Skyrim to piąta część popularnego cyklu gier RPG studia Bethesda Softworks. Podobnie jak w przypadku poprzednich odsłon, gracz ma okazję wcielić się w bohatera, który ma za zadanie ocalić świat przed zagładą.',
      mainPicture: 'SkyrimXBOX.jpg',
      inStock: 0,
      platform: Platform.XBOX,
      price: 159.99,
      pictureOne: 'Skyrim_1.jpg',
      pictureTwo: 'Skyrim_2.jpg',
      pictureThree: 'Skyrim_3.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a37255',
      name: 'The Elder Scrolls V: Skyrim',
      language: 'PL',
      pegi: 18,
      description:
        'The Elder Scrolls V: Skyrim to piąta część popularnego cyklu gier RPG studia Bethesda Softworks. Podobnie jak w przypadku poprzednich odsłon, gracz ma okazję wcielić się w bohatera, który ma za zadanie ocalić świat przed zagładą.',
      mainPicture: 'SkyrimPS.jpg',
      inStock: 0,
      platform: Platform.PLAYSTATION,
      price: 159.99,
      pictureOne: 'Skyrim_1.jpg',
      pictureTwo: 'Skyrim_2.jpg',
      pictureThree: 'Skyrim_3.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17254',
      name: 'Elden Ring',
      language: 'PL',
      pegi: 18,
      description:
        'Elden Ring to gra akcji RPG osadzona w otwartym świecie, stworzona przez studio FromSoftware, znane z takich tytułów jak Dark Souls czy Sekiro: Shadows Die Twice. Za produkcję odpowiada Hidetaka Miyazaki, a wydawcą jest firma Bandai Namco.',
      mainPicture: 'EldenRingPC.jpg',
      inStock: 1,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'EldenRing_1.jpg',
      pictureTwo: 'EldenRing_2.jpg',
      pictureThree: 'EldenRing_3.jpg',
      pictureFour: 'EldenRing_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a27254',
      name: 'Elden Ring',
      language: 'PL',
      pegi: 18,
      description:
        'Elden Ring to gra akcji RPG osadzona w otwartym świecie, stworzona przez studio FromSoftware, znane z takich tytułów jak Dark Souls czy Sekiro: Shadows Die Twice. Za produkcję odpowiada Hidetaka Miyazaki, a wydawcą jest firma Bandai Namco.',
      mainPicture: 'EldenRingXBOX.jpg',
      inStock: 1,
      platform: Platform.XBOX,
      price: 159.99,
      pictureOne: 'EldenRing_1.jpg',
      pictureTwo: 'EldenRing_2.jpg',
      pictureThree: 'EldenRing_3.jpg',
      pictureFour: 'EldenRing_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a37254',
      name: 'Elden Ring',
      language: 'PL',
      pegi: 18,
      description:
        'Elden Ring to gra akcji RPG osadzona w otwartym świecie, stworzona przez studio FromSoftware, znane z takich tytułów jak Dark Souls czy Sekiro: Shadows Die Twice. Za produkcję odpowiada Hidetaka Miyazaki, a wydawcą jest firma Bandai Namco.',
      mainPicture: 'EldenRingPS.jpg',
      inStock: 1,
      platform: Platform.PLAYSTATION,
      price: 159.99,
      pictureOne: 'EldenRing_1.jpg',
      pictureTwo: 'EldenRing_2.jpg',
      pictureThree: 'EldenRing_3.jpg',
      pictureFour: 'EldenRing_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17253',
      name: 'Red Dead Redemption 2',
      language: 'PL',
      pegi: 18,
      description:
        'Red Dead Redemption 2 to wyprodukowana przez Rockstar Games gra akcji, stanowiąca trzecią część serii Red Dead. Akcja gry została osadzona w roku 1899, czyli w czasach, w których Dziki Zachód zaczyna powoli znikać.',
      mainPicture: 'RDR2PC.jpg',
      inStock: 5,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'RDR2_1.jpg',
      pictureTwo: 'RDR2_2.jpg',
      pictureThree: 'RDR2_3.jpg',
      pictureFour: 'RDR2_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a27253',
      name: 'Red Dead Redemption 2',
      language: 'PL',
      pegi: 18,
      description:
        'Red Dead Redemption 2 to wyprodukowana przez Rockstar Games gra akcji, stanowiąca trzecią część serii Red Dead. Akcja gry została osadzona w roku 1899, czyli w czasach, w których Dziki Zachód zaczyna powoli znikać.',
      mainPicture: 'RDR2XBOX.jpg',
      inStock: 5,
      platform: Platform.XBOX,
      price: 159.99,
      pictureOne: 'RDR2_1.jpg',
      pictureTwo: 'RDR2_2.jpg',
      pictureThree: 'RDR2_3.jpg',
      pictureFour: 'RDR2_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a37253',
      name: 'Red Dead Redemption 2',
      language: 'PL',
      pegi: 18,
      description:
        'Red Dead Redemption 2 to wyprodukowana przez Rockstar Games gra akcji, stanowiąca trzecią część serii Red Dead. Akcja gry została osadzona w roku 1899, czyli w czasach, w których Dziki Zachód zaczyna powoli znikać.',
      mainPicture: 'RDR2PS.jpg',
      inStock: 5,
      platform: Platform.PLAYSTATION,
      price: 159.99,
      pictureOne: 'RDR2_1.jpg',
      pictureTwo: 'RDR2_2.jpg',
      pictureThree: 'RDR2_3.jpg',
      pictureFour: 'RDR2_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17252',
      name: 'Assassins Creed Valhalla',
      language: 'PL',
      pegi: 18,
      description: `Assassin's Creed Valhalla to kolejna odsłona popularnego cyklu sandboksowych gier akcji studia Ubisoft, nad którą pieczę sprawuje ekipa z kanadyjskiego oddziału dewelopera (m.in. Assassin's Creed IV: Black Flag, Assassin's Creed: Rogue, Assassin's Creed: Unity, Assassin's Creed: Syndicate oraz Assassin's Creed: Odyssey).`,
      mainPicture: 'ACValhallaPC.jpg',
      inStock: 2,
      platform: Platform.PC,
      price: 99.99,
      pictureOne: 'ACValhalla_1.jpg',
      pictureTwo: 'ACValhalla_2.jpg',
      pictureThree: 'ACValhalla_3.jpg',
      pictureFour: 'ACValhalla_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a27252',
      name: 'Assassins Creed Valhalla',
      language: 'PL',
      pegi: 18,
      description: `Assassin's Creed Valhalla to kolejna odsłona popularnego cyklu sandboksowych gier akcji studia Ubisoft, nad którą pieczę sprawuje ekipa z kanadyjskiego oddziału dewelopera (m.in. Assassin's Creed IV: Black Flag, Assassin's Creed: Rogue, Assassin's Creed: Unity, Assassin's Creed: Syndicate oraz Assassin's Creed: Odyssey).`,
      mainPicture: 'ACValhallaXBOX.jpg',
      inStock: 2,
      platform: Platform.XBOX,
      price: 99.99,
      pictureOne: 'ACValhalla_1.jpg',
      pictureTwo: 'ACValhalla_2.jpg',
      pictureThree: 'ACValhalla_3.jpg',
      pictureFour: 'ACValhalla_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a37252',
      name: 'Assassins Creed Valhalla',
      language: 'PL',
      pegi: 18,
      description: `Assassin's Creed Valhalla to kolejna odsłona popularnego cyklu sandboksowych gier akcji studia Ubisoft, nad którą pieczę sprawuje ekipa z kanadyjskiego oddziału dewelopera (m.in. Assassin's Creed IV: Black Flag, Assassin's Creed: Rogue, Assassin's Creed: Unity, Assassin's Creed: Syndicate oraz Assassin's Creed: Odyssey).`,
      mainPicture: 'ACValhallaPS.jpg',
      inStock: 2,
      platform: Platform.PLAYSTATION,
      price: 99.99,
      pictureOne: 'ACValhalla_1.jpg',
      pictureTwo: 'ACValhalla_2.jpg',
      pictureThree: 'ACValhalla_3.jpg',
      pictureFour: 'ACValhalla_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17251',
      name: 'Baldurs Gate 3',
      language: 'PL',
      pegi: 18,
      description:
        'Baldur’s Gate III to trzecia odsłona kultowej serii cRPG, która zadebiutowała w 1998 roku. Za produkcję gry odpowiada studio Larian, znane z takich tytułów jak Divinity: Original Sin czy Divinity: Original Sin II.',
      mainPicture: 'BaldursGate3.jpg',
      inStock: 4,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'BaldursGate3_1.jpg',
      pictureTwo: 'BaldursGate3_2.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17250',
      name: 'FIFA 22',
      language: 'PL',
      pegi: 18,
      description:
        'FIFA 22 to kolejna odsłona popularnego cyklu gier piłkarskich, nad którym pieczę sprawuje studio EA Sports. Produkcja została wydana przez firmę Electronic Arts i jest dostępna na platformach PC, PS4, PS5, XONE i XSX.',
      mainPicture: 'FIFA22PC.jpg',
      inStock: 6,
      platform: Platform.PC,
      price: 159.99,
      pictureOne: 'FIFA22_1.jpg',
      pictureTwo: 'FIFA22_2.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8b17246',
      name: 'FIFA 22',
      language: 'PL',
      pegi: 18,
      description:
        'FIFA 22 to kolejna odsłona popularnego cyklu gier piłkarskich, nad którym pieczę sprawuje studio EA Sports. Produkcja została wydana przez firmę Electronic Arts i jest dostępna na platformach PC, PS4, PS5, XONE i XSX.',
      mainPicture: 'FIFA22XBOX.jpg',
      inStock: 6,
      platform: Platform.XBOX,
      price: 159.99,
      pictureOne: 'FIFA22_1.jpg',
      pictureTwo: 'FIFA22_2.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17247',
      name: 'FIFA 22',
      language: 'PL',
      pegi: 18,
      description:
        'FIFA 22 to kolejna odsłona popularnego cyklu gier piłkarskich, nad którym pieczę sprawuje studio EA Sports. Produkcja została wydana przez firmę Electronic Arts i jest dostępna na platformach PC, PS4, PS5, XONE i XSX.',
      mainPicture: 'FIFA22PS.jpg',
      inStock: 6,
      platform: Platform.PLAYSTATION,
      price: 159.99,
      pictureOne: 'FIFA22_1.jpg',
      pictureTwo: 'FIFA22_2.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17249',
      name: 'Mario Kart 8 Deluxe',
      language: 'ENG',
      pegi: 3,
      description:
        'Mario Kart 8 Deluxe to wyścigowa gra zręcznościowa, stanowiąca rozwinięcie wydanej w 2014 roku gry Mario Kart 8. Produkcja została wydana przez firmę Nintendo i jest dostępna na platformie Nintendo Switch.',
      mainPicture: 'MarioKart8.jpg',
      inStock: 8,
      platform: Platform.NINTENDO,
      price: 159.99,
      pictureOne: 'MarioKart8_1.jpg',
      pictureTwo: 'MarioKart8_2.jpg',
      pictureThree: 'MarioKart8_3.jpg',
      pictureFour: 'MarioKart8_4.jpg',
    },
    {
      id: 'fd105551-0f0d-4a9f-bc41-c559c8a17248',
      name: 'The Legend of Zelda: Breath of the Wild',
      language: 'ENG',
      pegi: 12,
      description:
        'The Legend of Zelda: Breath of the Wild to wydana na platformę Switch gra akcji należąca do cyklu The Legend of Zelda. Tytuł został wyprodukowany przez japońską firmę Nintendo, która jest również wydawcą gry.',
      mainPicture: 'Zelda.jpg',
      inStock: 0,
      platform: Platform.NINTENDO,
      price: 159.99,
      pictureOne: 'Zelda_1.jpg',
      pictureTwo: 'Zelda_2.jpg',
      pictureThree: 'Zelda_3.jpg',
      pictureFour: 'Zelda_4.jpg',
    },
  ];
}

async function seed() {
  await Promise.all(
    getProducts().map((productData) => {
      return db.product.create({ data: productData });
    }),
  );
}

seed();
